package core.cpu;

public enum OPCode {
    
    ADC(OPCode.REGULAR),
    AND(OPCode.REGULAR),
    ASL(OPCode.REGULAR),
    BCC(OPCode.BRANCH),
    BCS(OPCode.BRANCH),
    BEQ(OPCode.BRANCH),
    BIT(OPCode.REGULAR),
    BMI(OPCode.BRANCH),
    BNE(OPCode.BRANCH),
    BPL(OPCode.BRANCH),
    BRK(OPCode.BRANCH),
    BVC(OPCode.BRANCH),
    BVS(OPCode.BRANCH),
    CLC(OPCode.REGULAR),
    CLD(OPCode.REGULAR),
    CLI(OPCode.REGULAR),
    CLV(OPCode.REGULAR),
    CMP(OPCode.REGULAR),
    CPX(OPCode.REGULAR),
    CPY(OPCode.REGULAR),
    DEC(OPCode.REGULAR),
    DEX(OPCode.REGULAR),
    DEY(OPCode.REGULAR),
    EOR(OPCode.REGULAR),
    INC(OPCode.REGULAR),
    INX(OPCode.REGULAR),
    INY(OPCode.REGULAR),
    JMP(OPCode.BRANCH),
    JSR(OPCode.BRANCH),
    LDA(OPCode.REGULAR),
    LDX(OPCode.REGULAR),
    LDY(OPCode.REGULAR),
    LSR(OPCode.REGULAR),
    NOP(OPCode.REGULAR),
    ORA(OPCode.REGULAR),
    PHA(OPCode.REGULAR),
    PHP(OPCode.REGULAR),
    PLA(OPCode.REGULAR),
    PLP(OPCode.REGULAR),
    ROL(OPCode.REGULAR),
    ROR(OPCode.REGULAR),
    RTI(OPCode.BRANCH),
    RTS(OPCode.BRANCH),
    SBC(OPCode.REGULAR),
    SEC(OPCode.REGULAR),
    SED(OPCode.REGULAR),
    SEI(OPCode.REGULAR),
    STA(OPCode.REGULAR),
    STX(OPCode.REGULAR),
    STY(OPCode.REGULAR),
    TAX(OPCode.REGULAR),
    TAY(OPCode.REGULAR),
    TSX(OPCode.REGULAR),
    TXA(OPCode.REGULAR),
    TXS(OPCode.REGULAR),
    TYA(OPCode.REGULAR),
    XXX(OPCode.ILLEGAL),
    ASO(OPCode.ILLEGAL),
    RLA(OPCode.ILLEGAL),
    LSE(OPCode.ILLEGAL),
    RRA(OPCode.ILLEGAL),
    AXS(OPCode.ILLEGAL),
    LAX(OPCode.ILLEGAL),
    DCM(OPCode.ILLEGAL),
    INS(OPCode.ILLEGAL),
    ALR(OPCode.ILLEGAL),
    ARR(OPCode.ILLEGAL),
    XAA(OPCode.ILLEGAL),
    OAL(OPCode.ILLEGAL),
    SAX(OPCode.ILLEGAL),
    SKB(OPCode.ILLEGAL),
    SKW(OPCode.ILLEGAL),
    HLT(OPCode.ILLEGAL),
    TAS(OPCode.ILLEGAL),
    SAY(OPCode.ILLEGAL),
    XAS(OPCode.ILLEGAL),
    AXA(OPCode.ILLEGAL),
    ANC(OPCode.ILLEGAL),
    LAS(OPCode.ILLEGAL);

    public static final int ILLEGAL = 2;
    public static final int BRANCH = 1;
    public static final int REGULAR = 0;
    public final int type;
    
    OPCode(int type) {
        this.type = type;
    }
}
